### ISSUE TITLE
Implement union operator.

### ISSUE THREAD

**Issue by juanpa097** [Treepat/Treepat#18]
**Summary.**
This union operator acts as an or and the same way as the `|` operator works in regular expressions.

**Example**
`(A | B | C)`
This means the this expression will match any node with nam `A`, `B` or `C`.

**Comment by juanpa097** [comment]
@jpavlich Professor, can you help us clarify what is the use case of the union (`|`) operator.

**Comment by juanpa097** [comment]
@jpavlich Hoiwis

**Comment by johan-smc** [comment]
@jpavlich hi

**Comment by johan-smc** [comment]
no se

**Comment by juanpa097** [comment]
![](https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy.gif)
