### ISSUE TITLE
visitSibling function is returning more Siblings than necessary.

### ISSUE THREAD

**Issue by juanpa097** [Treepat/Treepat#24]
**Describe the bug**
The function `visitSibling` in the class `TreepatVisitorImplementation` is returning more siblings than usual.

**Additional context**
Check test `should have many node, three children, two sibling and then up` in the file `src/test/java/ast/ASTNodesKtTest.kt`

**Comment by DorianMoreno** [comment]
This Issue isn't relevant anymore, is it?

**Comment by johan-smc** [comment]
> This Issue isn't relevant anymore, is it?

Yes it is because we create more classes than necessaries

**Comment by DorianMoreno** [comment]
Are you sure it wasn't an error originated from the test? As `showASTNodeFrame()` shows an accurate number of sibling nodes.
