### ISSUE TITLE
Breath Closure operation might not be concruent with language specification.

### ISSUE THREAD

**Issue by juanpa097** [Treepat/Treepat#54]
**Describe the bug**
In the Treepat Language Specification there are two times the breath closure is mention. The first times states that:
> The `*` operator applied after an expression indicates that such pattern can repeat zero or more times at the same level in the tree.

The second is a diagram of the automata to solve the `*` operator:
<img width="726" alt="Screenshot 2020-03-21 at 9 27 54 pm" src="https://user-images.githubusercontent.com/15882623/77241009-d59ac300-6bba-11ea-870f-33d6f55c1f2f.png">
In this definition requires the pattern to appear at least once because there is no direct transition from the initial state to final state.

Right now we are implementing the first deffiniton, but the second definition might make more sense for the context.

**To Reproduce**
### Current Behaviour 
**Input Target Tree**
```
A:1
    C:2
    B:3
    B:4
    C:5
    B:6
```
**Input Treepat Expression**
```
A
    B*
```
**Output**
```
A:1
```
```
A:1
    B:3
    B:4
```
```
A:1
```
```
A:1
    B:6
```
### Expected Behaviour 
**Input Target Tree**
```
A:1
    C:2
    B:3
    B:4
    C:5
    B:6
```
**Input Treepat Expression**
```
A
    B*
```
**Output**
```
A:1
    B:3
    B:4
    C:5
    B:6
```
```
A:1
    B:6
```

**Comment by juanpa097** [comment]
@jpavlich Can you help us clarify this issue? What would be the expected matches for the following input?

**Input Target Tree**
```
A:1
    C:2
    B:3
    B:4
    C:5
    B:6
```
**Input Treepat Expression**
```
A
    B*
```
Thank you! 😊

**Comment by jpavlich** [comment]
> **Describe the bug**
> In the Treepat Language Specification there are two times the breath closure is mention. The first times states that:
> 
> > The `*` operator applied after an expression indicates that such pattern can repeat zero or more times at the same level in the tree.
> 
> The second is a diagram of the automata to solve the `*` operator:
> <img alt="Screenshot 2020-03-21 at 9 27 54 pm" width="726" src="https://user-images.githubusercontent.com/15882623/77241009-d59ac300-6bba-11ea-870f-33d6f55c1f2f.png">
> In this definition requires the pattern to appear at least once because there is no direct transition from the initial state to final state.

The figure is not very clear, but the first state is also a final state, thus it accepts the pattern zero or more times

**Comment by jpavlich** [comment]
> @jpavlich Can you help us clarify this issue? What would be the expected matches for the following input?
> 
> **Input Target Tree**
> 
> ```
> A:1
>     C:2
>     B:3
>     B:4
>     C:5
>     B:6
> ```
> 
> **Input Treepat Expression**
> 
> ```
> A
>     B*
> ```

It should only match
```  
A
```

B* would only match B's that are at the beginning of the children list. Since there is a C at the beginning, B* would not match it.

**Comment by johan-smc** [comment]
> > @jpavlich Can you help us clarify this issue? What would be the expected matches for the following input?
> > **Input Target Tree**
> > ```
> > A:1
> >     C:2
> >     B:3
> >     B:4
> >     C:5
> >     B:6
> > ```
> > 
> > 
> > **Input Treepat Expression**
> > ```
> > A
> >     B*
> > ```
> 
> It should only match
> 
> ```
> A
> ```
> 
> B* would only match B's that are at the beginning of the children list. Since there is a C at the beginning, B* would not match it.

@jpavlich according to that definition, then what would be the output of:
  **Input Treepat Expression**
```
  A:1
      C:2
      B:3
      B:4
      C:5
      B:6
```
  
  
  **Input Treepat Expression**
```
  A
      B
```
