### ISSUE TITLE
Can't compile with openjdk-11

### ISSUE THREAD

**Issue by jpavlich** [Treepat/Treepat#70]
**To Reproduce**
1. Setup: Linux Mint 19.3 
2. javac 11.0.6 (openjdk)
3. Apache Maven 3.6.0
4. Run `mvn compile`
5. Got this error: 

```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project Treepat: Fatal error compiling: error: release version 12 not supported -> [Help 1]
```

**Comment by juanpa097** [comment]
For the Java files in the project we are Java 12, this configuration is located in the line 103 of the [`pom.xml` file](https://github.com/Treepat/Treepat/blob/dev/pom.xml)
We recommend the user's to install [OpenJDK 12](https://jdk.java.net/archive/) and make sure maven has the right configuration, for example when we run `mvn --version` we get:
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T14:39:06-05:00)
Maven home: /opt/homebrew/Cellar/maven/3.5.0/libexec
Java version: 12.0.2, vendor: AdoptOpenJDK
Java home: /Library/Java/JavaVirtualMachines/adoptopenjdk-12.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
```
And we can see that in Java version we have: `12.0.2, vendor: AdoptOpenJDK`

But we have to add the prerequisites to the README file and for that we are creating a new issue  #72
